import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./materialdesignicons.min.css";
import "./line.css";
import "./tobii.min.css";
import "./choices.min.css";
import "./tiny-slider.css";
import "./tailwind.min.css";
import Header from "@/sections/header";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light scroll-smooth" dir="ltr">
      <body className="dark:bg-slate-900">
        <Header />
        {children}

        <Script src="/assets/libs/tobii/js/tobii.min.js" />
        <Script src="/assets/libs/tiny-slider/min/tiny-slider.js" />
        <Script src="/assets/libs/choices.js/public/assets/scripts/choices.min.js" />
        <Script src="/assets/libs/feather-icons/feather.min.js" />
        <Script src="/assets/js/plugins.init.js" />
        <Script src="/assets/js/app.js" />
      </body>
    </html>
  );
}
