import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import "./css/materialdesignicons.min.css";
import "./css/line.css";
import "./css/tobii.min.css";
import "./css/choices.min.css";
import "./css/tiny-slider.css";
import "./css/tailwind.min.css";
import Header from "@/sections/header";
import Script from "next/script";
import Footer from "@/sections/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Easify Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light scroll-smooth" dir="ltr">
      <body className="dark:bg-slate-900">
        <Header />
        {children}
        <Footer />
        <Script src="/assets/libs/tobii/js/tobii.min.js" />
        <Script src="/assets/libs/tiny-slider/min/tiny-slider.js" />
        <Script src="/assets/libs/choices.js/public/assets/scripts/choices.min.js" />
        <Script src="/assets/libs/feather-icons/feather.min.js" />
        <Script src="/assets/js/plugins.init.js" />
        <Script src="/assets/js/app.js" />
      </body>
    </html>
  );
}
